//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by MGDT Templates
//

import Foundation

extension Notification.Name {
    static let ___VARIABLE_moduleName___DidChangedNotification = Notification.Name(rawValue: 
        "com.tingdao.app.___VARIABLE_moduleName___DidChangedNotification")
}

extension Notification.UserInfoKey {
    static var ___VARIABLE_moduleName___DidChangedNotificationBehaviorKey: Notification.UserInfoKey<___VARIABLE_moduleName___Engine.ChangeBehavior> {
        return Notification.UserInfoKey(key: "com.tingdao.app.___VARIABLE_moduleName___DidChangedNotification.ChangeBehavior")
    }
}

final class ___VARIABLE_moduleName___Engine {

    // MARK: - 枚举定义 -
    %ENUM_DEFINE%

    // MARK: - 数据处理 -
    %DATA_PROCESS%
    
    // MARK: - 请求接口数据 -
    %REQUEST_DATA%
    
    %OPERATION_BEHAVIOR%
}
