//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by MGDT Templates
//

import UIKit

final class ___VARIABLE_moduleName___ViewController: DTBaseViewController {

    // MARK: - properties -

    %TABLE_VIEW%

    %TABLE_VIEW_REFRESH%

    let engine = ___VARIABLE_moduleName___Engine.init()

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()

        %TABLE_VIEW_LOAD%

        NotificationCenter.default.addObserver(
            self,
            selector: #selector(datasDidChange),
            name: .___VARIABLE_moduleName___DidChangedNotification,
            object: nil
        )
    }

    %REQUEST_DATA%
    
    // MARK: - Data sync -
    
    @objc func datasDidChange(_ notification: Notification) {
        let behavior = notification.getUserInfo(
            for: .___VARIABLE_moduleName___DidChangedNotificationBehaviorKey
        )
        self.syncDataToUI(for: behavior)
    }

    // MARK: - UI -
    %SYNC_DATA_TO_UI%

    %DELETE_OPERATION%
}

%TABLE_VIEW_DELEGATE%