//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by MGDT Templates
//

import UIKit

class  ___VARIABLE_moduleName___ListCell: %PARENT_CLASS% {
    override func awakeFromNib() {
        super.awakeFromNib()
        selectionStyle = .none

        %CALL_SETUP_RIGHT_BUTTONS%
        // TODO: 在这里写UI初始化相关逻辑
    }

    %RIGHT_BUTTONS_CREATE_AND_USE%
}

%RIGHT_BUTTONS_DELEGATE%