//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by MGDT Templates
//

import Foundation
 
struct ___VARIABLE_moduleName___Model: Codable {
    let id: String
    // TODO: use https://app.quicktype.io/ web tool to gonerate model by json
}

// MARK: - Extensions -

extension ___VARIABLE_moduleName___Model: Hashable {
    func hash(into hasher: inout Hasher) {
        return hasher.combine(id.hashValue)
    }
}

extension ___VARIABLE_moduleName___Model: Equatable {
    public static func == (lhs: ___VARIABLE_moduleName___Model, rhs: ___VARIABLE_moduleName___Model) -> Bool {
        return lhs.id == rhs.id
    }
}
