//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by MGDT Templates
// 
//  

import Foundation

/// ___VARIABLE_moduleName___ListRequest
/// 接口文档地址：
/// 接口文档参数说明：
final class ___VARIABLE_moduleName___ListRequest: DTBaseRequest {

    private(set) var nextPage: Int
    private(set) var pageCount: Int
    
    required init(nextPage: Int, pageCount: Int) {
        self.nextPage = nextPage
        self.pageCount = pageCount
        super.init()
    }
    
    override func requestUrl() -> String {
        return ""
    }
    
    override func requestArgument() -> Any? {
        var argument = [String: Any]()
        argument["offset"] = String(nextPage)
        argument["count"] = String(pageCount)
        return packageRequestArgument(argument)
    }
    
    // override func requestMethod() -> YTKRequestMethod {
    //     return .POST
    // }
    
    // override func requestTimeoutInterval() -> TimeInterval {
    //     return TimeInterval(15)
    // }
}
