//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by MGDT Templates
// 
//  

import Foundation

/// ___VARIABLE_moduleName___Request
/// 接口文档地址：
/// 接口文档参数说明：
final class ___VARIABLE_moduleName___Request: DTBaseRequest {

    // private(set) var id: String
    
    // required init(id: String) {
    //     self.id = id
    //     super.init()
    // }
    
    override func requestUrl() -> String {
        return ""
    }
    
    override func requestArgument() -> Any? {
        var argument = [String: Any]()
        // argument["id"] = id
        return packageRequestArgument(argument)
    }
    
    // override func requestMethod() -> YTKRequestMethod {
    //     return .POST
    // }
    
    // override func requestTimeoutInterval() -> TimeInterval {
    //     return TimeInterval(15)
    // }
}
